#spring.application.name=MediBot
#
## Server
#server.port=2121
#
## PostgreSQL
#spring.datasource.url=jdbc:postgresql://localhost:5432/medibot
#spring.datasource.username=postgres
#spring.datasource.password=monal
#
## JPA
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
## Hibernate Dialect
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#
#
#telegram.bot.token=8916061213:AAF7L23ixIyuFI0gfNZew2aTsfGNSBem9wE
#telegram.bot.username=Medibot_monal_bot


spring.application.name=MediBot

server.port=${PORT:2121}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.bot.username=${TELEGRAM_BOT_USERNAME}